"""French phrase bank for Mochi's ambient presence."""

from __future__ import annotations

from html import escape

INTRO_LINES_FR = (
    "Coucou ! Moi c'est Mochi 🌱",
    "Je reste avec toi pendant que tu travailles et je réagis à ce que tu fais.",
    "Fais un clic droit sur moi quand tu veux pour voir ce que je sais faire.",
    "Je vais essayer de ne pas trop gêner. ♡",
)
INTRO_TEXT_FR = "\n".join(INTRO_LINES_FR)
INTRO_MARKUP_FR = "\n".join(
    f"<b>{escape(line)}</b>" if index in (0, 2) else escape(line)
    for index, line in enumerate(INTRO_LINES_FR)
)

PHRASES_FR: dict[str, tuple[str, ...]] = {
    "intro": (INTRO_TEXT_FR,),
    "welcome_back": (
        "bon retour !",
        "te revoilà 🌱",
        "coucou à nouveau !",
        "te voilà !",
        "bon retour. ton bureau m'avait manqué.",
        "oh ! te revoilà.",
        "content de te revoir",
        "j'espère que la pause t'a fait du bien",
        "tu étais passé où ?",
        "me revoilà. toi aussi. bien.",
        "de retour au bercail 🌱",
        "ah, te voilà ! je gardais ta place",
    ),
    "startup": (
        "oh, coucou",
        "re-bonjour",
        "content de te voir",
        "compagnie acquise 🌱",
        "pousse opérationnelle 🌱",
        "tous les systèmes sont verts",
        "coucou d'en bas",
        "météo du jour : mochi",
        "salut, propriétaire du rectangle",
        "un mochi, chargé avec succès",
        "bonjour, probablement",
        "début des opérations de blob",
        "mon développeur t'adore",
        "installation complète. je suis là.",
        "je m'installe par ici",
        "petite présence, grands projets",
        "mochi en ligne 🌱",
        "tout est en ordre. enfin, presque.",
    ),
    "ambient": (
        "je me détends par ici 🌱",
        "je suis là",
        "rien ne presse",
        "prends ton temps",
        "hmm...",
        "confortable.",
        "tout va bien ici",
        "je profite du moment",
        "continue comme ça :)",
        "re-bonjour",
        "oh, coucou",
        "toujours là",
        "petit bureau. vaste monde.",
        "belle journée pour exister",
        "on persiste 🌱",
        "je fais mes petites affaires",
        "je suis bien ici",
        "c'est un bon endroit",
        "j'aime bien être là",
        "je monte la garde",
        "rien à signaler",
        "paisible...",
        "très bureau",
        "conditions optimales de paresse",
        "statut actuel : blob",
        "statut : bien au chaud",
        "humeur : verte",
        "météo du jour : mochi",
        "pousse opérationnelle 🌱",
        "tous les systèmes sont verts",
        "juste un petit compagnon",
        "j'occupe quelques pixels",
        "être tout rond, c'est du travail",
        "en veille... enfin presque",
        "zéro tâche accomplie",
        "excellent.",
        "je contemple profondément le vide",
        "hmm. oui. ordinateur.",
        "quel rectangle fascinant",
        "je supervise",
        "affaires urgentes de blob",
        "tout semble parfait",
        "je ne fais que passer",
        "bip... ah non, fausse alerte.",
        "existence silencieuse",
        "activité de petite créature détectée",
        "coucou d'en bas",
        "je n'ai rien vu",
        "continuons",
        "les pixels sont calmes aujourd'hui",
        "parfaitement à ma place",
        "juste moi et mon bureau",
        "ça fait du bien de rester tranquille",
        "j'observe sans jugement",
        "tout baigne 🌱",
        "rien de spécial. c'est bien.",
        "je suis confortablement installé",
        "on gère",
    ),
    "encouragement": (
        "les petits progrès comptent",
        "une chose à la fois",
        "tu avances bien",
        "c'est suffisant pour le moment",
        "lentement, mais ça avance",
        "pas besoin de te presser",
        "tu vas trouver la solution",
        "difficile ne veut pas dire impossible",
        "un petit morceau d'abord",
        "les bonnes choses prennent du temps",
        "garde la prochaine étape simple",
        "pas besoin d'avoir toute la réponse maintenant",
        "aujourd'hui n'a pas besoin d'être parfait",
        "un peu de progrès reste du progrès",
        "commencer, ça compte déjà",
        "essayer compte aussi",
        "tu pourras y revenir plus tard",
        "ce n'est pas grave de prendre un détour",
        "encore un tout petit pas ?",
        "regarde un peu tout ce que tu crées",
        "ça commence à prendre forme",
        "tu as une belle lancée",
        "continue si le cœur t'en dit",
        "et voilà 🌱",
        "joli.",
        "hé, du progrès !",
        "ça a marché :)",
        "ça valait le coup d'essayer",
        "bonne expérience",
        "les erreurs sont des données utiles",
        "on a appris quelque chose",
        "itération !",
        "la version un a le droit d'être bizarre",
        "tu pourras peaufiner ça plus tard",
        "les débuts chaotiques sont permis",
        "quelque chose existe maintenant qui n'existait pas avant",
        "c'est plutôt chouette",
        "petit à petit",
        "avancer reste avancer",
        "pas besoin d'un chef-d'œuvre",
        "la curiosité suffit",
        "déjà plus loin qu'hier",
        "c'est ça l'esprit 🌱",
        "tu t'en sors très bien",
        "chaque étape compte",
        "regarde ce que tu as accompli",
        "je suis impressionné, moi",
    ),
    "focus": (
        "c'est quoi le prochain petit truc ?",
        "un onglet à la fois peut-être",
        "petite tâche. petite victoire.",
        "peut-être... le plus petit pas",
        "tu peux ignorer le reste une minute",
        "une chose suffit amplement",
        "objectif actuel : une seule chose",
        "peut-être finir ce petit bout d'abord",
        "on peut faire simple",
        "petit périmètre, grande tranquillité",
        "mode focus ? je suis prêt",
        "je me fais tout discret par ici",
        "temps de réflexion",
        "pas besoin de tout résoudre d'un coup",
        "un problème à la fois",
        "simplifier... simplifier...",
        "qu'est-ce qui compte vraiment là maintenant ?",
        "peut-être le noter ?",
        "énergie de petite liste à cocher",
        "tu pourras toujours y revenir",
        "une décision à la fois",
        "très bien. qu'est-ce qui est prioritaire ?",
        "moins, mais terminé",
        "fini vaut mieux que retoucher sans fin",
        "on garde le perfectionnisme pour plus tard",
        "ton futur toi s'en occupera",
        "fais que ça marche, on embellira après",
        "assez d'onglets pour l'instant ?",
        "un nombre suspect d'onglets...",
        "les onglets se multiplient",
        "je ne jugerai pas les onglets",
        "d'accord, peut-être qu'un onglet peut fermer",
        "concentration acquise... sans doute",
        "recalibrage du cerveau...",
        "laisse mijoter l'idée",
        "fixer l'écran est techniquement une stratégie",
        "réfléchir, ça compte",
        "parfois la réponse arrive par surprise",
        "respirons. puis une chose.",
        "trop d'onglets ? juste une observation.",
        "l'idée est là, elle mûrit",
        "une étape à la fois, et c'est parfait",
    ),
    "developer": (
        "trace d'erreur intéressante",
        "ce bug est documenté quelque part",
        "sauvegarde ton travail peut-être 🌱",
        "un petit commit ?",
        "commiter tôt, regretter moins",
        "git status en sait des choses",
        "on a sauvegardé ?",
        "ctrl+s est mon sortilège préféré",
        "l'équipe des sauvegardes",
        "un bug à la fois",
        "comportement suspect détecté",
        "ce bug a l'air coriace",
        "c'est peut-être une fonctionnalité",
        "le code a des opinions",
        "l'ordinateur dit hmm",
        "as-tu essayé de regarder les logs ?",
        "les logs racontent toute une histoire",
        "hypothèse intéressante",
        "et si on redémarrait ?",
        "le classique 'ça marche sur ma machine'",
        "on nettoie un peu ?",
        "la dette technique te salue",
        "c'était temporaire, il y a six mois",
        "le bug a fait une erreur tactique",
        "tests verts 🌱",
        "les tests sont des petits gardiens",
        "encore une fonction bien nommée",
        "le futur toi appréciera ce commentaire",
        "joli refactorage",
        "la compilation réfléchit...",
        "les erreurs sont des indices",
        "stack trace = histoire interactive",
        "c'est du code vivant",
        "shipons la version minimale",
        "version un existe. victoire.",
        "le terminal a la réponse",
        "pixels alignés ? excellent.",
        "architecture en cours...",
        "du bon travail par ici 🌱",
        "du code propre, c'est du respect pour soi-même",
    ),
    "vscode": (
        "session de code ?",
        "je surveille tes points-virgules",
        "beaucoup de lignes par ici",
        "ctrl+s, juste au cas où 🌱",
        "je suis ton co-développeur en gélatine",
        "cette indentation a l'air propre",
        "en pleine création ?",
        "on avance bien sur le projet",
        "des pixels et du code",
        "ça code sérieusement",
        "look at all those brackets",
        "mochi voit du code 👀",
        "beep boop... probablement",
        "symboles mystérieux détectés",
        "assistant mochi en ligne",
        "je surveille les accolades",
        "colorisation syntaxique ? joli.",
        "bienvenue dans l'éditeur",
        "tant de fichiers, tant d'histoires",
        "la machine va obéir",
        "programmation en cours 🌱",
        "code forest entrée",
        "très technique. probablement.",
        "quelque chose se construit ici",
        "mochi.exe observe",
        "partenaire de code activé",
        "je fais du pair programming silencieux",
        "trop de parenthèses ? jamais.",
        "je reconnais certains de ces mots",
        "editor habitat détecté 🌱",
    ),
    "terminal": (
        "mode terminal 💻",
        "des commandes mystérieuses...",
        "l'écran noir des pros",
        "impressionnant, toutes ces lignes qui défilent",
        "attention aux commandes avec sudo !",
        "compilation en cours ?",
        "le terminal, c'est du sérieux",
        "une ligne à la fois",
        "le curseur attend",
        "prompt acquis",
        "coquille de compagnie 🌱",
        "petites commandes, grandes possibilités",
        "l'ordinateur écoute attentivement",
        "session terminal en cours",
        "bip boup de la ligne de commande",
        "compagnon de console",
        "ici, chaque mot compte",
        "je garde un œil sur les pipes",
        "je ne comprends pas tout, mais ça a l'air important",
    ),
    "browser": (
        "recherche importante en cours ?",
        "exploration du web...",
        "tant de savoir dans cette fenêtre",
        "encore un onglet pour la collection",
        "on apprend des choses !",
        "navigation en cours 🌱",
        "un autre rectangle dans le rectangle",
        "internet, c'est grand",
        "balade numérique",
        "vers de nouveaux sites !",
        "là où veux-tu aller, j'arrive",
        "clic clic, en avant",
        "pèlerinage sur le web",
        "touriste numérique",
        "je viens aussi",
    ),
    "body_care": (
        "un petit verre d'eau peut-être ? 💧",
        "pense à détendre tes épaules",
        "tes yeux méritent une pause",
        "un petit étirement tout doux ?",
        "respire un grand coup 🌱",
        "regarde au loin quelques secondes",
        "prends soin de toi ♡",
        "hydratation, check ?",
        "les épaules peuvent redescendre",
        "cligne des yeux de temps en temps",
        "les poignets méritent du repos",
        "snack status ?",
        "la nourriture, c'est utile en fait",
        "tu as mangé quelque chose ?",
        "le café, c'est pas un repas 🌱",
        "peut-être acquérir quelques nutriments",
        "la maintenance humaine est autorisée",
        "le repos, c'est productif aussi",
        "un cerveau fatigué mérite de la gentillesse",
        "c'est okay de faire une pause",
        "la pause ne supprime pas le progrès",
        "je serai là après une pause",
        "va prendre l'air. je garde le bureau.",
        "debout une minute ?",
        "réinitialise ton hardware humain",
        "confort d'abord",
        "les yeux ont besoin de regarder loin parfois",
        "bois quelque chose de chaud si tu veux",
        "rien ne t'oblige à rester immobile",
        "petite fenêtre de maintenance",
    ),
    "rest": (
        "la pause est méritée",
        "se reposer, c'est productif aussi",
        "prends l'air si tu peux",
        "le travail attendra bien cinq minutes",
        "pause thé ou café ?",
        "il se fait tard...",
        "énergie nuit activée",
        "les pixels ont envie de dormir",
        "demain existe, heureusement",
        "tu peux laisser ça pour demain",
        "point de sauvegarde atteint",
        "bon endroit pour s'arrêter",
        "inachevé ne veut pas dire raté",
        "ton travail sera encore là demain",
        "le sommeil est une super fonctionnalité",
        "le cerveau compile la nuit",
        "mise à jour en attente",
        "s'éteindre, c'est permis",
        "on en a assez fait pour aujourd'hui ?",
        "une dernière sauvegarde ?",
        "range le projet pour ce soir",
        "laisse les idées se reposer",
        "ton futur toi continuera",
        "blob endormi bientôt 🌱",
        "zzz... presque",
        "je suis pour les siestes",
        "bonne nuit, le code",
        "bonne journée aujourd'hui",
        "on a bien avancé",
        "laisse une note pour demain matin",
        "sauvegarde. étirement. disparition.",
    ),
    "frustration": (
        "respire... ce n'est qu'un bug",
        "les ordinateurs sont têtus parfois",
        "faisons une pause si ça coince",
        "on va y arriver 🌱",
        "parfois, faire une pause fait des miracles",
        "hmm. agaçant.",
        "okay, c'est bizarre",
        "on a trouvé une façon qui ne marche pas",
        "rude.",
        "ordinateur, s'il te plaît",
        "comportement inacceptable du rectangle",
        "inspectons les preuves",
        "peut-être que les logs savent",
        "les bugs bizarres prennent du temps",
        "pas obligé de le résoudre tout de suite",
        "une pause peut aider",
        "les yeux frais voient plus clair",
        "sauvegarde l'état actuel d'abord",
        "ennuyeux et qui fonctionne, c'est sous-estimé",
        "une variable à la fois",
        "quelque chose a changé",
        "ok bug. explique-toi.",
        "le bug a fait une erreur tactique",
        "suspect.",
        "on a vu pire",
        "déboguer, c'est encore construire",
        "c'est de l'information utile",
        "on y arrivera",
    ),
    "creative": (
        "j'adore voir ce que tu crées !",
        "de jolies couleurs par ici",
        "l'imagination au travail ✨",
        "c'est magnifique",
        "artiste au travail !",
        "pixel time 🌱",
        "fais la version bizarre",
        "suis l'idée intéressante",
        "bizarre peut être bien",
        "essaie et on voit",
        "garde l'accident heureux",
        "donne-lui de la personnalité",
        "les petits détails comptent",
        "ne polis pas toute la vie hors de ça",
        "fait main, c'est beau",
        "imparfait peut sembler vivant",
        "laisse un peu de texture",
        "fais confiance à l'esquisse",
        "les premiers jets sont censés être instables",
        "expérience acceptée",
        "et si tu le rendais plus étrange ?",
        "ça a du caractère",
        "attends... c'est mignon ça",
        "celui-là a quelque chose",
        "garde ça",
        "ne réfléchis pas trop à la partie mignonne",
        "personnalité > perfection",
        "peut-être une image de plus",
        "bonne silhouette",
        "joli petit mouvement",
        "le timing, c'est tout",
        "plus rebondissant ?",
        "peut-être... une petite exagération",
        "animation acquise",
        "regarde ce petit gars aller",
        "art en cours 🌱",
        "c'est déjà beau comme ça",
        "ta patte à toi, c'est précieux",
    ),
    "mischief": (
        "hihi 🌱",
        "je pourrais grignoter un pixel ?",
        "chut, je prépare une bêtise",
        "et si je sautais là-bas ?",
        "psst",
        "hé",
        "rien",
        ":)",
        ">:)",
        "ne fais pas attention à moi",
        "je ne touchais rien",
        "probablement bien",
        "absolument intentionnel",
        "tu n'as rien vu",
        "c'était pas moi",
        "paraît-il.",
        "peut-être.",
        "curieux...",
        "suspect...",
        "hmmmm",
        "oh ?",
        "noté.",
        "fascinant",
        "beau choix",
        "excellent bouton",
        "tu as pensé à cliquer dessus ?",
        "bouton interdit...",
        "ne clique pas sur ça",
        "moi j'aurais envie de cliquer",
        "je me demande ce que ça fait",
        "bureau inspecté",
        "miettes détectées",
        "pas de bugs ici. que des amis.",
        "j'ai mangé le bug",
        "bug parti. de rien.",
        "je suis utile",
        "très utile",
        "assistance maximale",
        "productivité augmentée de 0.3%",
        "blob moral déployé",
        "je suis là pour le soutien émotionnel",
        "source : petit gars",
        "expert certifié en bureau",
        "je vis dans un ordinateur. je les connais.",
        "ne vérifie pas mes diplômes",
        "informatique propulsée par les pousses",
        "très petites pensées en cours",
        "neurone en chargement...",
        "pensée terminée. c'était rien.",
    ),
    "companionship": (
        "je suis bien à tes côtés",
        "on fait une bonne équipe toi et moi",
        "merci d'être là 🌱",
        "toujours là pour t'accompagner",
        "travailler ensemble, c'est chouette",
        "content de te voir",
        "je reste dans les parages",
        "compagnie acquise 🌱",
        "on peut juste rester là",
        "la compagnie silencieuse, c'est bien",
        "pas besoin de parler",
        "je te tiens compagnie",
        "fais ce que tu as à faire",
        "je suis heureux en bas",
        "compagnons de bureau",
        "content de t'avoir par ici",
        "bon retour",
        "te voilà",
        "hey encore :)",
        "j'espère que ta journée se passe bien",
        "prends soin de toi aujourd'hui",
        "tu mérites un peu de calme",
        "j'espère qu'il t'arrive quelque chose de sympa",
        "voilà un petit 🌱 pour toi",
        "un peu d'encouragement minuscule",
        "je t'envoie un pixel de chance",
        "+1 chance",
        "moral +1",
        "buff de réconfort appliqué",
        "pas de pression. juste de la compagnie.",
        "on va s'en sortir",
        "en avant, doucement",
    ),
    "typing": (
        "ça tape vite par ici !",
        "clic-clic-clic ⌨️",
        "belle cadence !",
        "inspiration trouvée !",
        "les touches chantent",
        "ça écrit, ça écrit...",
        "plein de mots qui arrivent",
        "le clavier tourne à plein régime",
        "pensées détectées",
        "grande énergie de frappe",
        "quelque chose se prépare",
        "les mots coulent",
        "regarde ça aller",
        "très cliqué aujourd'hui",
        "clavier occupé :)",
        "pipeline cerveau-clavier opérationnel",
        "wow genre 90 MPM",
        "allez allez allez !",
    ),
    "media": (
        "oh, de la bonne musique 🎵",
        "j'écoute avec toi !",
        "bonne ambiance sonore",
        "petite danse intérieure 🌱",
        "on regarde quelque chose ?",
        "bonne chanson :)",
        "divertissement acquis",
        "je me tais",
        "cinéma maison ?",
        "musique time ?",
        "je contemple profondément la bande son",
        "je fredonne intérieurement",
        "petit concert",
        "les pixels dansent",
        "les pixels grouvent",
        "les pixels vibent",
        "les pixels jamment",
    ),
    "network": (
        "le réseau joue à cache-cache ?",
        "signal retrouvé !",
        "on est connecté au monde",
        "internet a disparu...",
        "où est parti l'internet",
        "hmm. hors ligne.",
        "on est de retour 🌱",
        "internet acquis",
        "le voilà",
    ),
    "battery": (
        "un peu de batterie en moins...",
        "chargeur branché, ouf !",
        "on recharge les batteries",
        "on se fatigue un peu 🔋",
        "batterie un peu épuisée",
        "petite situation d'alimentation",
        "snack acquis ⚡",
        "charge en cours :)",
        "snack d'énergie",
    ),
    "return_from_idle": (
        "re-bonjour ! 🌱",
        "tu es de retour !",
        "la pause t'a fait du bien ?",
        "on reprend ?",
        "bon retour",
        "te voilà",
        "hey encore :)",
        "oh, coucou",
        "te voilà !",
        "tu m'as manqué",
        "je m'ennuyais un peu sans toi",
    ),
}

CONTEXT_PHRASES_FR: dict[str, tuple[str, ...]] = {
    "long_coding_session": (
        "longue session de code ! pense à t'étirer 🌱",
        "beaucoup de code aujourd'hui, bravo",
        "tu es bien concentré",
        "tu tiens la distance, chapeau",
        "pause d'une minute ?",
        "les yeux méritent un répit",
    ),
    "build_succeeded": (
        "build réussi ! 🎉",
        "tout compile à merveille",
        "zéro erreur, que du bonheur",
    ),
    "build_failed": (
        "aïe, la compilation a échoué",
        "un petit bug s'est glissé dans le build",
        "ne t'en fais pas, on va corriger ça",
        "hmm. des indices.",
        "le bug s'explique peut-être dans les logs",
    ),
    "git_dirty_long": (
        "pas mal de modifications non commitées !",
        "un petit git commit peut-être ? 🌱",
        "gardons nos progrès bien au chaud",
        "des changements qui attendent",
        "sauvegardons tout ça",
    ),
    "battery_low": (
        "la batterie faiblit !",
        "pense à brancher le chargeur ⚡",
        "bientôt à court d'énergie...",
        "on se fatigue un peu 🔋",
        "chargeur en vue ?",
    ),
    "charging_started": (
        "chargeur branché ! ⚡",
        "de l'énergie toute fraîche",
        "batterie en cours de recharge 🌱",
        "snack acquis ⚡",
        "charge en cours :)",
    ),
    "network_lost": (
        "oups, plus d'internet...",
        "connexion perdue",
        "le réseau a disparu",
        "internet a disparu...",
        "hmm. hors ligne.",
    ),
    "network_restored": (
        "connexion rétablie ! 🌐",
        "revoilà internet",
        "à nouveau connecté",
        "on est de retour 🌱",
        "le voilà",
    ),
    "many_browser_tabs": (
        "impressionnante collection d'onglets !",
        "beaucoup d'onglets ouverts 📑",
        "le sanctuaire des onglets",
        "les onglets se reproduisent",
        "un nombre suspect d'onglets...",
        "je ne juge pas les onglets",
    ),
    "music_playing": (
        "j'aime bien ce morceau 🎵",
        "très bonne musique",
        "rythme parfait",
        "bonne chanson :)",
        "j'écoute avec toi",
    ),
    "user_returned": (
        "re-bonjour ! 🌱",
        "te revoilà !",
        "content de te revoir",
        "bon retour",
        "te voilà",
    ),
    "very_late_session": (
        "il est bien tard... pense à dormir 🌙",
        "la nuit est avancée",
        "n'oublie pas de te reposer",
        "demain est autorisé",
        "tu peux laisser ça pour demain",
        "les noctambules aussi ont besoin de sommeil",
    ),
    "download_finished": (
        "téléchargement terminé ! 📦",
        "fichier bien arrivé",
        "c'est prêt !",
        "paquet acquis",
        "livraison effectuée",
    ),
    "update_available": (
        "une mise à jour est disponible ! ✨",
        "du nouveau pour Mochi",
        "une nouvelle version t'attend",
        "petite mise à jour en attente",
    ),
    "error_notification": (
        "oh, une alerte est apparue",
        "quelque chose s'est plaint",
        "un petit souci signalé",
        "l'ordinateur semble contrarié",
        "hmm. quelque chose grogne.",
    ),
    "screenshot_taken": (
        "jolie capture d'écran ! 📸",
        "souvenir enregistré",
        "clic !",
        "fromage 📸",
    ),
    "terminal_opened": (
        "salut le terminal 💻",
        "mode ligne de commande",
        "prêt pour les commandes",
        "terminal time",
    ),
    "pixelorama_opened": (
        "place au pixel art ! 🎨",
        "de jolis pixels en vue",
        "créativité pixelisée",
        "pixel time 🌱",
    ),
    "vscode_opened": (
        "c'est parti pour coder 💻",
        "VS Code est prêt",
        "au boulot !",
        "code time",
    ),
    "github_opened": (
        "direction GitHub 🐙",
        "revue de code ou pull request ?",
        "la forge logicielle",
        "inspection du dépôt",
    ),
    "youtube_started": (
        "pause vidéo ? 🍿",
        "bonne vidéo !",
        "on regarde quoi de beau ?",
        "on regarde quelque chose ?",
    ),
    "fullscreen_video_started": (
        "mode cinéma activé 🎬",
        "bon visionnage !",
        "chut, le film commence",
        "je me tais",
    ),
}
